fragment ProjectParts on Project {
  __typename
  title
  slug
  date
  featured
  status
  heroImage
  gallery {
    __typename
    image
    alt
    caption
  }
  excerpt
  description
  techStack
  metrics {
    __typename
    roi
    engagement
    efficiency
    custom1Label
    custom1Value
    custom2Label
    custom2Value
  }
  projectUrl
  githubUrl
  category
  color
}

fragment PostParts on Post {
  __typename
  title
  slug
  date
  status
  featured
  heroImage
  excerpt
  content
  tags
  category
  readTime
  author
  seo {
    __typename
    title
    description
    keywords
  }
}

fragment GalleryImageParts on GalleryImage {
  __typename
  title
  image
  alt
  description
  category
  tool
  date
  tags
  featured
}

fragment SiteSettingsParts on SiteSettings {
  __typename
  site {
    __typename
    title
    description
    author
    email
    logo
    favicon
  }
  social {
    __typename
    twitter
    linkedin
    github
    instagram
  }
  seo {
    __typename
    defaultTitle
    defaultDescription
    defaultImage
  }
}
