[build]
  command = "npm run build"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[build.environment]
  NEXT_TELEMETRY_DISABLED = "1"

[[headers]]
  for = "/admin/*"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"

[[headers]]
  for = "*.yml"
  [headers.values]
    Content-Type = "text/yaml"
    Cache-Control = "public, max-age=0, must-revalidate"

[[headers]]
  for = "/admin/config.yml"
  [headers.values]
    Content-Type = "text/yaml"
    Cache-Control = "public, max-age=0, must-revalidate"

# Security headers for all pages
[[headers]]
  for = "/*"
  [headers.values]
    # Remove X-Powered-By header for security
    X-Powered-By = ""
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "camera=(), microphone=(), geolocation=()"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' https://identity.netlify.com https://res.cloudinary.com https://widget.cloudinary.com https://upload-widget.cloudinary.com; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com; font-src 'self' https://fonts.gstatic.com; img-src 'self' data: blob: https://res.cloudinary.com https://images.unsplash.com https://cloudinary.com; media-src 'self' https://res.cloudinary.com; connect-src 'self' https://api.cloudinary.com https://res.cloudinary.com https://identity.netlify.com wss://identity.netlify.com https://*.netlify.com https://*.netlify.app; frame-src 'self' https://identity.netlify.com https://widget.cloudinary.com https://upload-widget.cloudinary.com; object-src 'none'; base-uri 'self'; form-action 'self' https://identity.netlify.com; frame-ancestors 'none'; upgrade-insecure-requests"