backend:
  name: github
  repo: kalabar794/jpc
  branch: main
  base_url: https://api.netlify.com
  auth_endpoint: auth

# Use Cloudinary for image optimization and CDN delivery
media_library:
  name: cloudinary
  config:
    cloud_name: dqltlwqi2
    api_key: 194453126296877

# Fallback local paths (Cloudinary will override these)
media_folder: public/uploads
public_folder: /uploads

collections:
  - name: posts
    label: Blog Posts
    folder: content/posts
    create: true
    slug: "{{slug}}"
    # Uses global Cloudinary configuration
    editor:
      preview: false
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Slug", name: "slug", widget: "string"}
      - {label: "Date", name: "date", widget: "datetime"}
      - {label: "Hero Image", name: "heroImage", widget: "image", required: false}
      - {label: "Excerpt", name: "excerpt", widget: "text"}
      - {label: "Category", name: "category", widget: "string"}
      - {label: "Tags", name: "tags", widget: "list"}
      - {label: "Featured", name: "featured", widget: "boolean", default: false}
      - {label: "Status", name: "status", widget: "select", options: ["draft", "published"], default: "draft"}
      - {label: "Body", name: "body", widget: "markdown"}
      - label: "SEO"
        name: "seo"
        widget: "object"
        fields:
          - {label: "Title", name: "title", widget: "string", required: false}
          - {label: "Description", name: "description", widget: "text", required: false}
          - {label: "Keywords", name: "keywords", widget: "string", required: false}

  - name: projects
    label: Projects
    folder: content/projects
    create: true
    slug: "{{slug}}"
    # Uses global Cloudinary configuration
    editor:
      preview: false
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Slug", name: "slug", widget: "string"}
      - {label: "Date", name: "date", widget: "datetime"}
      - {label: "Hero Image", name: "heroImage", widget: "image", required: false}
      - {label: "Excerpt", name: "excerpt", widget: "text"}
      - {label: "Category", name: "category", widget: "string"}
      - {label: "Tags", name: "tags", widget: "list"}
      - {label: "Featured", name: "featured", widget: "boolean", default: false}
      - {label: "Status", name: "status", widget: "select", options: ["draft", "published"], default: "draft"}
      - {label: "Demo URL", name: "demoUrl", widget: "string", required: false}
      - {label: "GitHub URL", name: "githubUrl", widget: "string", required: false}
      - {label: "Body", name: "body", widget: "markdown"}

  - name: galleries
    label: Galleries
    files:
      - name: ai_gallery
        label: AI Gallery Images
        file: content/galleries/ai-gallery.md
        fields:
          - {label: "Title", name: "title", widget: "string", default: "AI Gallery"}
          - label: "Images"
            name: "images"
            widget: "list"
            fields:
              - {label: "Title", name: "title", widget: "string"}
              - {label: "Image", name: "image", widget: "image"}
              - {label: "Description", name: "description", widget: "text", required: false}
              - {label: "Prompt", name: "prompt", widget: "text", required: false}
              - {label: "Model", name: "model", widget: "string", default: "DALL-E 3", required: false}
              - {label: "Style", name: "style", widget: "string", required: false}
              - {label: "Tags", name: "tags", widget: "list", required: false}
              - {label: "Featured", name: "featured", widget: "boolean", default: false}
              - {label: "Date", name: "date", widget: "datetime"}
      
      - name: photography_gallery
        label: Photography Gallery Images
        file: content/galleries/photography-gallery.md
        fields:
          - {label: "Title", name: "title", widget: "string", default: "Photography Gallery"}
          - label: "Images"
            name: "images"
            widget: "list"
            fields:
              - {label: "Title", name: "title", widget: "string"}
              - {label: "Image", name: "image", widget: "image"}
              - {label: "Description", name: "description", widget: "text", required: false}
              - {label: "Location", name: "location", widget: "string", required: false}
              - {label: "Camera", name: "camera", widget: "string", required: false}
              - {label: "Settings", name: "settings", widget: "string", required: false}
              - {label: "Category", name: "category", widget: "select", options: ["landscape", "portrait", "street", "nature", "architecture", "abstract"], default: "landscape"}
              - {label: "Tags", name: "tags", widget: "list", required: false}
              - {label: "Featured", name: "featured", widget: "boolean", default: false}
              - {label: "Date", name: "date", widget: "datetime"}

  - name: about_page
    label: About Page
    files:
      - name: about
        label: About Page Content
        file: content/pages/about.md
        fields:
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Hero Title", name: "heroTitle", widget: "string"}
          - {label: "Hero Subtitle", name: "heroSubtitle", widget: "string"}
          - {label: "Bio", name: "bio", widget: "text"}
          - label: "Expertise"
            name: "expertise"
            widget: "list"
            fields:
              - {label: "Name", name: "name", widget: "string"}
              - {label: "Gradient", name: "gradient", widget: "string"}
          - label: "Experience"
            name: "experience"
            widget: "list"
            fields:
              - {label: "Company", name: "company", widget: "string"}
              - {label: "Role", name: "role", widget: "string"}
              - {label: "Description", name: "description", widget: "text"}
              - {label: "Icon", name: "icon", widget: "string"}

  - name: settings
    label: Settings
    files:
      - name: site
        label: Site Settings
        file: content/settings/site.md
        fields:
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Description", name: "description", widget: "text"}
          - {label: "Author", name: "author", widget: "string"}
          - label: "Social Links"
            name: "social"
            widget: "object"
            fields:
              - {label: "Twitter", name: "twitter", widget: "string", required: false}
              - {label: "LinkedIn", name: "linkedin", widget: "string", required: false}
              - {label: "GitHub", name: "github", widget: "string", required: false}
              - {label: "Email", name: "email", widget: "string", required: false}